modLoader = "javafml"
loaderVersion = "[40,)"
license = "GNU GPL 3.0"
[[mods]]
modId = "nbtdumpsterfire"
version = "${file.jarVersion}"
displayName = "NBTDumpsterFire"
displayURL="https://github.com/GibberishDev/NBT-Dumpster-Fire"
authors = "GibbDev"
description = '''
Small clientside mod for datapack and modpack developers. Allows to print out in chat or store in json file nbt data of items and entities.
'''
[[dependencies.nbtdumpsterfire]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nbtdumpsterfire]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
