modLoader = "javafml"
loaderVersion = "[40,)"
license = "GNU GPL 3.0"
[[mods]]
modId = "nbtdumpsterfire"
version = "${file.jarVersion}"
displayName = "NBTDumpsterFire"
#displayURL="http://example.com/" #optional
#logoFile="nbtdumpsterfire.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors = "GibbDev" #optional
description = '''

'''
[[dependencies.nbtdumpsterfire]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nbtdumpsterfire]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
